### ISSUE TITLE
Tracking issue: to-do on the website

### ISSUE THREAD

**Issue by JustinyAhin** [Ajeso/Portfolio#4]
- [x] Create a README.md file (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)
- [x] Delete [.DS_Store](https://github.com/Ajeso/Portfolio/blob/main/.DS_Store) and [.DS_Store](https://github.com/Ajeso/Portfolio/blob/main/assets/.DS_Store)
- [x] Add a `.gitignore` file (https://www.atlassian.com/git/tutorials/saving-changes/gitignore)
- [x] Deploy the site to Netlify, or GitHub pages or Cloudflare or wherever looks good for you
- [x] Move [script.js](https://github.com/Ajeso/Portfolio/blob/main/script.js) to the assets folder
